version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    volumes:
      - .:/fastapi-app                  # Mount the current directory into /fastapi-app in the container
      - ./model:/fastapi-app/model       # Mount the model directory if needed (persists data)
    ports:
      - "8080:80"                   # Map local port 8000 to container port 80
    environment:
      - ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
